### ISSUE TITLE
Добавить документацию к функциям

### ISSUE THREAD

**Issue by Temmmmmo** [profcomff/timetable-api#105]
### Основная проблема
В файлах с различными методами и ручками есть много незадокументированных методов. Например, здесь: `calendar_backend/methods/image.py`.

### Задача
Необходимо разобраться в работе методов и задокументировать их. (Необязательно все, достаточно одного метода)

P.S. Примеры документации функции можно посмотреть, например, здесь `calendar_backend/methods/list_calendar.py`.

**Comment by grigoriev-semyon** [comment]
closed in #106
